### ISSUE TITLE
OST blue

### ISSUE THREAD

**Issue by NaoPross** [HBadertscher/OSTPresentation#1]
I snitched the code from this file for [this](https://github.com/HSR-Stud/HSRStud-Package/blob/master/build/oststud.pdf) and noticed that DarkBlue and Blue have the same values, which is not correct, right?

https://github.com/HBadertscher/OSTPresentation/blob/056d90a88323b268c48851d7a97f7b3ea7ca8c49/header/OSTColors.sty#L29

https://github.com/HBadertscher/OSTPresentation/blob/056d90a88323b268c48851d7a97f7b3ea7ca8c49/header/OSTColors.sty#L38

**Comment by HBadertscher** [comment]
Thanks for reporting - you are right of course. I corrected the color.

Side note: in the mean time, the marketing department has changed some colors slightly and added other colors in the official CI. I will update this in a separate commit later.

One more note: here, only the RGB colors are defined - which is fine for slides that are only viewed on a screen. For printing (e.g. a report), using the CMYK-colors is a lot better, as the difference between CMYK and RGB is quite noticable when printing.
